# Demo inference config of CTC inference with greedy search

task:
  type: "ctc_inference"
  export_path: "test_logs/debug"
  train_config: "config/training/conformer_ctc.yaml"
  chkpt_aver: true
  aver_best_k: 10
  descending: false # Specify whether metric of best models is descending or not 
  chkpt_name: null

testset:
  test_data: "sample_data/asr_train_data.json"
  config:
    batch_size: 23
    apply_segment: false
    feat_type: "torchscript_fbank"
    feat_config:
      torchscript: "tasks/debug/frontend.script"
      num_mel_bins: 80

decoding:
  type: "ctc_greedy_decoding"
  config:
    dummy: -1

streaming:
  is_encoder_streaming: false

trainer:
  accelerator: "gpu" 
  devices: 1 
  strategy: "ddp" 
