# Demo inference config of CTC inference with beam search

task:
  type: "ctc_inference"
  export_path: "test_logs/debug"
  train_config: "config/training/conformer_ctc.yaml"
  chkpt_aver: true
  aver_best_k: 10
  descending: false # Specify whether metric of best models is descending or not 
  chkpt_name: null

testset:
  test_data: "sample_data/asr_train_data.json"
  config:
    batch_size: 23
    apply_segment: false
    feat_type: "torchscript_fbank"
    feat_config:
      torchscript: "tasks/debug/frontend.script"
      num_mel_bins: 80

decoding:
  type: "ctc_lexicon_beam_decoding"
  config:
    nbest: 1
    beam_size: 16
    beam_size_token: null
    beam_threshold: 50
    sil_token: "<blank_id>"

trainer:
  accelerator: "gpu" 
  devices: 1 
  strategy: "ddp" 
