# Demo inference config of CTC task

task:
  type: "ctc_inference"
  export_path: "test_logs/debug"

testset:
  test_data: "sample_data/asr_train_data.json"
  config:
    batch_size: 24
    apply_segment: false
    feat_type: "torchscript_fbank"
    feat_config:
      torchscript: "sample_data/model/frontend.script"
      num_mel_bins: 64

decoding:
  type: "ctc_greedy_decoding"
  config:
    dummy: -1
