# Demo inference config of Rnnt inference with beam search

task:
  type: "pruned_rnnt_inference"
  export_path: "test_logs/debug"
  train_config: "config/training/zipformer_stateless_pruned_rnnt.yaml"
  chkpt_aver: true
  aver_best_k: 10
  descending: false # Specify whether metric of best models is descending or not 
  chkpt_name: null
  onnx_export: true

testset:
  test_data: "sample_data/asr_train_data.json"
  config:
    batch_size: 23
    apply_segment: false
    feat_type: "lhotes_fbank"
    feat_config:
      num_mel_bins: 80
      snip_edges: true # True for mnn deploy. otherwise for sherpa-onnx.

decoding:
  type: "rnnt_beam_decoding"
  config:
    beam_size: 4
    cutoff_top_k: 4

streaming:
  is_encoder_streaming: true
  encoder_streaming_setting:
    chunk_size: [32]
    left_context_frames: [128]

# If onnx_export=true, export config is required.
onnx_export_config:
  export_int8: false
  onnx_encoder_config:
    streaming: true
    using_dynamic_axe: false # If for sherpa-onnx, set as true.
    chunk_size: [32]
    left_context_frames: [128]
  onnx_predictor_config:
    for_mnn: true
  onnx_joiner_config:
    for_mnn: true

trainer:
  accelerator: "gpu" 
  devices: 1 
  strategy: "ddp" 
